name: Build entservices-apis on Ubuntu

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  ThunderComponents:
    runs-on: ubuntu-latest
    env:
       THUNDER_TOOLS_COMMIT_SHA: 53bdc7e2bb12497a228ff5694190c51e5dd533af
       THUNDER_COMMIT_SHA: ca7ad203398b3f065f9f494b89bc12038cd24f95

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build build-essential git

      - name: Clone ThunderTools
        run: |
          git clone -b R5_3 https://github.com/rdkcentral/ThunderTools.git
          cd ThunderTools
          git checkout ${{ env.THUNDER_TOOLS_COMMIT_SHA }}
          cd ..
          
      - name: Clone Thunder
        run: |
          git clone -b R5_3 https://github.com/rdkcentral/Thunder.git
          cd Thunder
          git checkout ${{ env.THUNDER_COMMIT_SHA }}
          cd ..
     
      - name: Install jsonref
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install jsonref

      - name: Build ThunderTools
        run: |
          cmake -G Ninja -S ThunderTools -B ThunderTools/build \
            -DCMAKE_INSTALL_PREFIX="${PWD}/install" \
            -DGENERIC_CMAKE_MODULE_PATH="${PWD}/install/include/Thunder/Modules"
          cmake --build ThunderTools/build --target install

      - name: Build Thunder
        run: |
          cmake -G Ninja -S Thunder -B Thunder/build \
            -DBINDING="127.0.0.1" \
            -DCMAKE_BUILD_TYPE="Debug" \
            -DCMAKE_INSTALL_PREFIX="install" \
            -DPORT="55555" \
            -DTOOLS_SYSROOT="${PWD}" \
            -DINITV_SCRIPT=OFF
          cmake --build Thunder/build
          sudo cmake --install Thunder/build
          sudo chown -R "$(id -u):$(id -g)" install

      - name: Build entservices-apis
        run: |
          cmake -G Ninja -S . -B build \
            -DCMAKE_INSTALL_PREFIX="${PWD}/install" \
            -DCMAKE_PREFIX_PATH="${PWD}/install" \
            -DCMAKE_CXX_FLAGS="-I${PWD}/install/include/Thunder" \
            -DCMAKE_MODULE_PATH="${PWD}/install/include/Thunder/Modules" \
            -DTOOLS_SYSROOT="${PWD}"
          cmake --build build --target install
